# This file was generated by GoReleaser. DO NOT EDIT.
cask "uradical-card" do
  name "uradical-card"
  desc "Generate branded social media cards with custom title and photo"
  homepage "https://github.com/uRadical/uradical-card"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uradical-card"

  on_macos do
    on_intel do
      url "https://github.com/uRadical/uradical-card/releases/download/v#{version}/uradical-card_#{version}_darwin_amd64.tar.gz"
      sha256 "844861504474848fe81ccc040c26c1b29617e2b5f1a7c496a8bf70bb6f645d3a"
    end
    on_arm do
      url "https://github.com/uRadical/uradical-card/releases/download/v#{version}/uradical-card_#{version}_darwin_arm64.tar.gz"
      sha256 "02444221f23e85613b8e1c87fbd1926bc406061eacf62bfbbaab1979fd00685e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/uRadical/uradical-card/releases/download/v#{version}/uradical-card_#{version}_linux_amd64.tar.gz"
      sha256 "018deb5ab651ee755e24aaf1abf1c4630ec56668ccf29915c3cac73d6bf1f511"
    end
    on_arm do
      url "https://github.com/uRadical/uradical-card/releases/download/v#{version}/uradical-card_#{version}_linux_arm64.tar.gz"
      sha256 "276198796edff600f1f7a26c93acb27679646a708e33dd139568f165955721a1"
    end
  end

  # No zap stanza required
end
