  class Mov2mp4 < Formula                                                                                                                                                                                                      
    desc "Command-line tool for converting MOV video files to MP4 format"                                                                                                                                                      
    homepage "https://github.com/uRadical/mov2mp4"                                                                                                                                                                             
    url "https://github.com/uRadical/mov2mp4.git",                                                                                                                                                                             
        using: :git,                                                                                                                                                                                                           
        tag: "v1.2.0",                                                                                                                                                                                                         
        revision: "c4da88bbf265b04d81e53666c4cae99e115837dc"                                                                                                                                                                   
    license "GPL-3.0"                                                                                                                                                                                                          
                                                                                                                                                                                                                               
    depends_on "ffmpeg"                                                                                                                                                                                                        
                                                                                                                                                                                                                               
    def install                                                                                                                                                                                                                
      bin.install "mov2mp4"                                                                                                                                                                                                    
    end                                                                                                                                                                                                                        
                                                                                                                                                                                                                               
    test do                                                                                                                                                                                                                    
      system "#{bin}/mov2mp4", "-h"                                                                                                                                                                                            
    end                                                                                                                                                                                                                        
  end 
