# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UradicalCard < Formula
  desc "Generate branded social media cards with custom title and photo"
  homepage "https://github.com/uRadical/uradical-card"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uRadical/uradical-card/releases/download/v1.1.2/uradical-card_1.1.2_darwin_amd64.tar.gz"
      sha256 "412602e179c1ad53061fe6d3efedceb905a640366537ab3ca46e81726aefbaba"

      def install
        bin.install "uradical-card"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uRadical/uradical-card/releases/download/v1.1.2/uradical-card_1.1.2_darwin_arm64.tar.gz"
      sha256 "2030fa16e0ac5fa00de92ef755dec34f07193a8a41d92f49b8df21e3b98b19f5"

      def install
        bin.install "uradical-card"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uRadical/uradical-card/releases/download/v1.1.2/uradical-card_1.1.2_linux_amd64.tar.gz"
      sha256 "44824572a6d8666d54deefeafe7d7c322f9bd434962a39bc2a5e3e812896074f"
      def install
        bin.install "uradical-card"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uRadical/uradical-card/releases/download/v1.1.2/uradical-card_1.1.2_linux_arm64.tar.gz"
      sha256 "545ff7932227bae37cc3fb45fa4741831c7ba9de0d1eb9d19f6fe42a7b355330"
      def install
        bin.install "uradical-card"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/uradical-card -h", 0)
  end
end
