# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UradicalCard < Formula
  desc "Generate branded social media cards with custom title and photo"
  homepage "https://github.com/uRadical/uradical-card"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uRadical/uradical-card/releases/download/v1.1.1/uradical-card_1.1.1_darwin_amd64.tar.gz"
      sha256 "757a8f7884aba4363872c21a00c6989c1f099cc7db61aab4417cd54321b6916b"

      def install
        bin.install "uradical-card"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uRadical/uradical-card/releases/download/v1.1.1/uradical-card_1.1.1_darwin_arm64.tar.gz"
      sha256 "6d146137b7d77636a4883b00ef692219b8f6e75139a78a5ae8338e7b3ce2df54"

      def install
        bin.install "uradical-card"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uRadical/uradical-card/releases/download/v1.1.1/uradical-card_1.1.1_linux_amd64.tar.gz"
      sha256 "9a5ca8302f4cd54a2e238fef6f92c7973ec0b3102a9241ff3107d1e613442ab8"
      def install
        bin.install "uradical-card"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uRadical/uradical-card/releases/download/v1.1.1/uradical-card_1.1.1_linux_arm64.tar.gz"
      sha256 "9cfec684e94815e6477139329e91615f85e5ecea9b3134638426a7ae8405c249"
      def install
        bin.install "uradical-card"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/uradical-card -h", 0)
  end
end
